name: Execute Unit Tests

on:
  push:
    paths:
      - '**.go'
      - '**.mod'
      - '**.sum'
  pull_request:
    paths:
      - '**.go'
      - '**.mod'
      - '**.sum'

env:
  PROXY_USER_SOCKS5: ${{ secrets.PROXY_USER_SOCKS5 }}
  PROXY_PASS_SOCKS5: ${{ secrets.PROXY_PASS_SOCKS5 }}
  PROXY_USER_HTTP: ${{ secrets.PROXY_USER_HTTP }}
  PROXY_PASS_HTTP: ${{ secrets.PROXY_PASS_HTTP }}
  PROXY_HOST_HTTP: ${{ secrets.PROXY_HOST_HTTP }}
  PROXY_PORT_HTTP: ${{ secrets.PROXY_PORT_HTTP }}
  PROXY_HOST_SOCKS5: ${{ secrets.PROXY_HOST_SOCKS5 }}
  PROXY_PORT_SOCKS5: ${{ secrets.PROXY_PORT_SOCKS5 }}

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.21.x]
        platform: [ubuntu-latest]
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.OS }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.OS }}-go-
      - name: Test
        run: go test -v ./...
