name: tests
on:
  push:
    paths:
      - '**.go'
      - '**.mod'
      - '**.sum'
  pull_request:
    paths:
      - '**.go'
  schedule:
    # run tests regularly at 3 AM every days to check if CloudFlare updated their detection
    - cron: '0 3 * * *'

env:
  PROXY_USER_SOCKS5: ${{ secrets.PROXY_USER_SOCKS5 }}
  PROXY_PASS_SOCKS5: ${{ secrets.PROXY_PASS_SOCKS5 }}
  PROXY_USER_HTTP: ${{ secrets.PROXY_USER_HTTP }}
  PROXY_PASS_HTTP:: ${{ secrets.PROXY_PASS_HTTP }}
  PROXY_HOST_HTTP: ${{ secrets.PROXY_HOST_HTTP }}
  PROXY_PORT_HTTP: ${{ secrets.PROXY_PORT_HTTP }}
  PROXY_HOST_SOCKS5: ${{ secrets.PROXY_HOST_SOCKS5 }}
  PROXY_PORT_SOCKS5: ${{ secrets.PROXY_PORT_SOCKS5 }}
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.21.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Test
        run: go test ./...
