name: tests
on:
  push:
    paths:
      - '**.go'
      - '**.mod'
      - '**.sum'
  pull_request:
    paths:
      - '**.go'
  schedule:
    # run tests regularly at 3 AM every days to check if CloudFlare updated their detection
    - cron: '0 3 * * *'

env:
  PROXY_USER: ${{ secrets.PROXY_USER }}
  PROXY_PASS: ${{ secrets.PROXY_PASS }}
  PROXY_HOST: ${{ secrets.PROXY_HOST }}
  PROXY_PORT_HTTP: ${{ secrets.PROXY_PORT_HTTP }}
  PROXY_PORT_SOCKS5: ${{ secrets.PROXY_PORT_SOCKS5 }}
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.21.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test
        run: go test ./...
